#!/usr/bin/bash

sbatch -c 8 --gpus=1 --wrap="python amazon.py"
sbatch -c 8 --gpus=1 --wrap="python amazon_ctr.py"
sbatch -c 8 --gpus=1 --wrap="python amazon_ctr_2.py"
sbatch -c 8 --gpus=1 --wrap="python amazon_ctr_255.py"
sbatch -c 8 --gpus=1 --wrap="python adult.py"
sbatch -c 8 --gpus=1 --wrap="python adult_ctr.py"
sbatch -c 8 --gpus=1 --wrap="python appetency.py"
sbatch -c 8 --gpus=1 --wrap="python appetency_ctr.py"
sbatch -c 8 --gpus=1 --wrap="python upselling.py"
sbatch -c 8 --gpus=1 --wrap="python upselling_ctr.py"
sbatch -c 8 --gpus=1 --wrap="python kick.py"
sbatch -c 8 --gpus=1 --wrap="python kick_ctr.py"
sbatch -c 8 --gpus=1 --wrap="python higgs.py"
sbatch -c 8 --gpus=1 --wrap="python higgs_ctr.py"